In [1]:
def isnum(n):
    n = str(n)
    if n.isdigit():
        return True
    return False
li = ["10","34","a"]
a = map(isnum,li)
list(a)
        
    

[True, True, False]

In [2]:
a = filter(isnum,li)
list(a)

['10', '34']

## lambda

In [3]:
a = lambda x,y: x+y
a(8,6)

14

In [5]:
a = lambda x : x**2
a(12)

144

## list comphrehension

In [6]:
a = [i**2 for i in range(1,11)]
a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [7]:
a=int(input())
for i in range(0,a+1):
    print(i**2)

7
0
1
4
9
16
25
36
49


In [9]:
n = int(input())
a = [i**2 for i in range(1,11)]
a


5


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [10]:
a = int(input())
b = 1
for i in range(1,a+1):
    b*=i
print(b)



    

6
720


In [17]:
import math
s = [math.factorial(i) for i in range(1,8)]
print(s)

[1, 2, 6, 24, 120, 720, 5040]


In [18]:
n = int(input())
m = 10
l = [n*i for i in range(1,m+1)]
l

5


[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

### file handling

* performing operations on a file is called file handling
* entering some data to a file is called as write to a file
* retriving data from a file is called as reading from a file
* we can perform append,delete operations on files


In [36]:
def writetoafile(filename,data):
    with open(filename,"w")as f:
        f.write(data)
    return
filename = "data.txt"
writetoafile(filename,"line1\nline2\n")
    

In [39]:

def readfromafile(filename):
    with open(filename,"r") as f:
        fd = f.read()
        f.close()
    return fd
readfromafile("kalyani.txt")


'line1\nline2\n'

In [41]:
def readfromafile(filename):
    with open(filename,"r") as f:
        fd = f.read()
        f.close()
    return fd
readfromafile("kalyani.txt")

'\ndef writetoafile(filename,data):\n    with open(filename,"w")as f:\n        f.write(data)\n    return\nfilename = "data.txt"\nwritetoafile(filename,"line1\\nline2\\n")\n    '

In [47]:
def appendtoafile(filename,data):
    with open(filename,"a")as f:
        for line in data:
            f.write("\n"+line)
        return
data = ["line3","line4","line5","line6"]
filename = "data.txt"
appendtoafile(filename,data)
    


### Numpy

* Numpy is an advanced library.
* Numpy --- numerical python
* Numpy is to perform mathematical and statistical operations
* The values are represented in the form of rows and columns.
* advantages of numpy when compared to lists:
    * it takes less time
    * performance will be high
    * occupies less memory


In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [5]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
### creating an array in particular range
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a=np.arange(1,10)
type(a)


numpy.ndarray

In [9]:
a-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
a*1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a2=np.array([[1,2,3,4],[5,6,7,8]])
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
a2.size

8

In [13]:
a2=np.array([[1,2,3,4],[5,6,7,8]],dtype=complex)
a2

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j]])

In [14]:
a2.dtype

dtype('complex128')

In [15]:
a.dtype

dtype('int32')

In [27]:
### combination of two arrays
a = np.array([[1,2,3,4],[4,5,6,7]])
b = np.array([[4,5,6,7],[3,4,5,6]])
a <b

array([[ True,  True,  True,  True],
       [False, False, False, False]])

In [28]:
a>b

array([[False, False, False, False],
       [ True,  True,  True,  True]])

In [31]:
a == b

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [32]:
a+b

array([[ 8, 10, 12, 14],
       [ 6,  8, 10, 12]])

In [33]:
a-b

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [34]:
a*b

array([[16, 25, 36, 49],
       [ 9, 16, 25, 36]])

In [35]:
a // b

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [36]:
a ** b

array([[   256,   3125,  46656, 823543],
       [    27,    256,   3125,  46656]], dtype=int32)

In [38]:
np.ones(5)

array([1, 1, 1, 1, 1])

In [39]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [40]:
np.ones([5,5],dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [41]:
np.zeros([5,5],dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [43]:
a

array([[4, 5, 6, 7],
       [3, 4, 5, 6]])

In [44]:
a[0]

array([4, 5, 6, 7])

In [45]:
a[0:,1]

array([5, 4])

In [46]:
a[0:1,1:2]            ## a[startngrow:endingrow,startingcolumn:endingcolumn]

array([[5]])

In [47]:
a[1:2,2:3]

array([[5]])

In [48]:
a[:,1:3]

array([[5, 6],
       [4, 5]])

In [49]:
a[:,2:3]

array([[6],
       [5]])

In [50]:
a[:,0:2]

array([[4, 5],
       [3, 4]])

In [51]:
a.shape

(2, 4)

In [52]:
a.ndim

2

In [53]:
a.nbytes

32

In [54]:
a.itemsize

4

In [56]:
b=np.arange(3,9)
b

array([3, 4, 5, 6, 7, 8])

In [57]:
b= np.arange(3,9)
b.reshape(2,3)

array([[3, 4, 5],
       [6, 7, 8]])

In [58]:
b = np.arange(3,9)
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [59]:
b.reshape(3,2)

array([[3, 4],
       [5, 6],
       [7, 8]])

In [60]:
b.reshape(2,3)

array([[3, 4, 5],
       [6, 7, 8]])

In [61]:
min(b)

3

In [62]:
np.std(b)

1.707825127659933

In [63]:
max(b)

8

In [64]:
np.mean(b)

5.5

In [65]:
np.sum(b)

33

In [66]:
np.var(b)

2.9166666666666665

In [67]:
np.cumsum(b)

array([ 3,  7, 12, 18, 25, 33], dtype=int32)

In [68]:
np.argmin(b) # represent the index

0

In [69]:
np.argmax(b)

5

In [73]:
a.transpose()

array([[4, 3],
       [5, 4],
       [6, 5],
       [7, 6]])

In [71]:
b

array([3, 4, 5, 6, 7, 8])

In [77]:
b=int(input())
d=0
i=0
while b!=0:
    binary=b%10
    d=d+binary*(2**i)
    b=b//10
    i=i+1
print("decimal number is:",d)
    

1101
decimal number is: 13


In [81]:
b=10
bin(b)

'0b1010'

In [ ]:
def firstdigit(n):
    while n>=10:
        n=n//10:
            return int(n)
